# Generated by Django 5.0.6 on 2025-10-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pricelistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='price',
        ),
    ]
