# Generated by Django 5.0.6 on 2025-10-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_pricelist_item_remove_pricelist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pricelistitem',
            old_name='item',
            new_name='name',
        ),
    ]
