# Generated by Django 5.0.6 on 2025-10-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_category_pricelist_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
