# Generated by Django 5.0.6 on 2025-10-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_pricelistitem_options_pricelistitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['price']},
        ),
    ]
