# Generated by Django 5.0.6 on 2025-10-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_pricelistitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistitem',
            name='order',
        ),
    ]
