# Generated by Django 5.0.6 on 2025-10-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_pricelistitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='name',
            new_name='category',
        ),
    ]
