# Generated by Django 5.0.6 on 2025-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_name_pricelist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
