# Generated by Django 5.0.6 on 2025-11-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_studioimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudioImage',
            new_name='Studio',
        ),
    ]
