# Generated by Django 5.0.6 on 2024-07-23 12:23

import datetime
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_text',
            field=tinymce.models.HTMLField(default=datetime.datetime(2024, 7, 23, 12, 23, 51, 209270, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
