# Generated by Django 5.0.6 on 2024-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_lead_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='Image', upload_to=''),
            preserve_default=False,
        ),
    ]
