# Generated by Django 5.0.6 on 2025-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='blog_images/logo-tertiary-altdark.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
